name: Test tagging

on:
  push:
    tags:
      - test-tag

jobs:
  tag:
   runs-on: ubuntu-latest

   steps: 
    # See: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#using-the-checkout-action
    - uses: actions/checkout@v1.0.0

    - name: Log tag push
      run: |
        echo "test-tag was pushed."
